### ISSUE TITLE
Latest builds are not making it to flathub

### ISSUE THREAD

**Issue by bancika** [flathub/com.diy_fever.DIYLayoutCreator#2]
@nbenitez @eduardosm since few months ago, my builds don't seem to be making it to flathub repo. The latest version I built is 4.27, but the repo is still at 4.24. Was anything changed that requires some update from my side? I've been adding versions as usual.

Here's the recent build that was supposed to update the repo to 4.27 https://buildbot.flathub.org/#/builders/32/builds/106822

Thanks!

**Comment by nbenitez** [comment]
I really don't know, the build is all green and the metainfo file seems right. Maybe @barthalion can help here.

**Comment by nbenitez** [comment]
It seems to be a general bug, it is affecting more people, see:
https://discourse.flathub.org/t/how-to-release-a-new-version-of-an-app/2850

Although flathub.org is not listing last releases, they are published and can be updated via flatpak commandline. 
You can check with `flatpak search DIYLayoutCreator` and update with `flatpak update com.diy_fever.DIYLayoutCreator`

Hopefully they'll fix flathub.org soon.

**Comment by barthalion** [comment]
There's an ongoing incident related to connectivity since Friday 26th at the datacenter hosting our website. There will be some wonkiness until it gets resolved on their end.
